### ISSUE TITLE
exchange venv with a poetry install to make installation easier 

### ISSUE THREAD

**Issue by Hir0ki** [Stegosawr/YTPlaylistDownloader#2]
I tried to install the programm on a linux machine, but the venv is different so i can't use it. There are also some libraries that are not used like discord and a few others. 
I would recommend that you use poetry for dependency managment 
https://poetry.eustace.io/
I would create a pull request but i don't know all dependencies.

**Comment by Stegosawr** [comment]
I will fix the import issue soon, it's just a a little squence problem.

Poetry looks great, but because I only use "youtube-dl" as a no-phython lib, there is no use for it here.
I will add poetry if I have more imports.

Thanks for suggesting.
